{% set name = "stepik-cli" %}
{% set version = "0.3.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/aryarm/stepik-cli.git
  git_rev: "{{ version }}"

build:
  number: 0
  entry_points:
    - stepik=stepik.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - click
    - colorama
    - html2text
    - pip
    - python
    - requests
  run:
    - click
    - colorama
    - html2text
    - python
    - requests

test:
  imports:
    - stepik
    - stepik.client
    - stepik.models
  commands:
    - stepik --help

about:
  home: "https://github.com/aryarm/stepik-cli"
  summary: "A Stepik CLI for students"
  doc_url: "https://github.com/aryarm/stepik-cli#README.md"
  dev_url: "https://github.com/aryarm/stepik-cli"

extra:
  recipe-maintainers:
    - aryarm
