{% set name = "stepik-cli" %}
{% set version = "0.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: ccc48b8098fb71ce474ee2767b2fe79f7461a6087561ba2b61bb7d6908995ad3

build:
  number: 0
  entry_points:
    - stepik=stepik.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - click
    - colorama
    - html2text
    - pip
    - python
    - requests
  run:
    - click
    - colorama
    - html2text
    - python
    - requests

test:
  imports:
    - stepik
    - stepik.client
    - stepik.models
  commands:
    - stepik --help

about:
  home: "https://github.com/aryarm/stepik-cli"
  summary: "A Stepik CLI for students"
  doc_url: "https://github.com/aryarm/stepik-cli#README.md"
  dev_url: "https://github.com/aryarm/stepik-cli"

extra:
  recipe-maintainers:
    - aryarm
